DROP VIEW IF EXISTS STATUS;
CREATE VIEW STATUS as
    SELECT CA_CLAVE as clave_catalogo ,CA_DESCRIPCION as descripcion ,CA_IMPORTE as importe ,CON_CLAVE as clave_contab FROM CATALOGO_COL WHERE CA_TIPO = 0;

DROP VIEW IF EXISTS DIRECCION;
CREATE VIEW DIRECCION as
    SELECT CA_CLAVE as clave_catalogo ,CA_DESCRIPCION as descripcion, CA_IMPORTE as importe ,CON_CLAVE as clave_contab FROM CATALOGO_COL WHERE CA_TIPO = 1;

DROP VIEW IF EXISTS TIPO_LOTE;
CREATE VIEW TIPO_LOTE as
    SELECT CA_CLAVE as clave_catalogo ,CA_DESCRIPCION as descripcion, CA_IMPORTE as importe ,CON_CLAVE as clave_contab FROM CATALOGO_COL WHERE CA_TIPO = 2;

DROP VIEW IF EXISTS REPORTE_CARGOS;
CREATE VIEW REPORTE_CARGOS as
SELECT CLIENTES.CL_NUMERO as Cliente, CLIENTES.CL_NOM as Nombre, CLIENTES.CL_DIREC as Direccion,CARGOS.CAR_FECHA as Fecha, SUM(CARGOS.CAR_IMPORTE) as Cargo_total
    FROM CLIENTES
    JOIN CARGOS ON CLIENTES.CL_NUMERO = CARGOS.CL_NUMERO
    GROUP BY CLIENTES.CL_NUMERO;

DROP VIEW IF EXISTS REPORTE_LOTES;
CREATE VIEW REPORTE_LOTES as
SELECT COLONO_LOTE.CL_NUMERO as Cliente, CLIENTES.CL_NOM as Nombre, COLONO_LOTE.L_MANZANA as Manzana, COLONO_LOTE.L_NUMERO as LOTE  FROM COLONO_LOTE
    JOIN CLIENTES ON CLIENTES.CL_NUMERO = COLONO_LOTE.CL_NUMERO
    ORDER BY Nombre;

DROP VIEW IF EXISTS REPORTE_IMPORTE_STATUS;
CREATE VIEW REPORTE_IMPORTE_STATUS as
SELECT CATALOGO_COL.CA_DESCRIPCION AS Status,SUM(CARGOS.CAR_IMPORTE) AS Importe_Total FROM CATALOGO_COL
    JOIN LOTE ON CATALOGO_COL.CA_CLAVE = LOTE.CA_CLAVE0
    JOIN CARGOS ON LOTE.L_MANZANA = CARGOS.L_MANZANA AND LOTE.L_NUMERO = CARGOS.L_NUMERO
    GROUP BY CATALOGO_COL.CA_TIPO, CATALOGO_COL.CA_DESCRIPCION;

DROP VIEW IF EXISTS REPORTE_CARGOS_FECHA;
CREATE VIEW REPORTE_CARGOS_FECHA as
SELECT CAR_FECHA as Fecha ,CLIENTES.CL_NUMERO as Cliente,CAR_IMPORTE as Importe FROM CARGOS
    JOIN CLIENTES ON CLIENTES.CL_NUMERO = CARGOS.CL_NUMERO
    ORDER BY Fecha;

DELIMITER $$

DROP PROCEDURE IF EXISTS OBTENER_REPORTE_CARGOS;
CREATE PROCEDURE OBTENER_REPORTE_CARGOS(IN P_FECHA date)
BEGIN
    IF ISNULL(P_FECHA) THEN
        SELECT * FROM reporte_cargos;
    ELSE
        SELECT * FROM reporte_cargos WHERE Fecha = P_FECHA;
    END IF;
END$$

DROP PROCEDURE IF EXISTS OBTENER_REPORTE_CARGOS;
CREATE PROCEDURE OBTENER_REPORTE_CARGOS(IN P_CLIENTE double)
BEGIN
    IF ISNULL(P_CLIENTE) THEN
        SELECT * FROM reporte_LOTEs;
    ELSE
        SELECT * FROM reporte_LOTEs WHERE Cliente = P_CLIENTE;
    END IF;
END$$

DROP PROCEDURE IF EXISTS OBTENER_IMPORTE_STATUS;
CREATE PROCEDURE OBTENER_IMPORTE_STATUS()
BEGIN
    SELECT * FROM REPORTE_IMPORTE_STATUS;
END$$

DROP PROCEDURE IF EXISTS OBTENER_IMPORTE_CARGOS_FECHA;
CREATE PROCEDURE OBTENER_IMPORTE_CARGOS_FECHA(IN P_FECHA_INICIO date,IN P_FECHA_FIN date)
BEGIN
    IF ISNULL(P_FECHA_INICIO) OR  isnull(P_FECHA_FIN) THEN
        SELECT * FROM reporte_LOTEs;
    ELSE
        SELECT * FROM REPORTE_CARGOS_FECHA WHERE Fecha BETWEEN P_FECHA_INICIO AND P_FECHA_FIN;
    END IF;
END$$

DROP FUNCTION IF EXISTS EXISTE_STATUS;
CREATE FUNCTION EXISTE_STATUS(clave_catalogo CHAR(3)) RETURNS BOOLEAN
BEGIN
    DECLARE existe BOOLEAN;
    SELECT COUNT(*) > 0 INTO existe
    FROM status
    WHERE status.clave_catalogo = clave_catalogo;
    RETURN existe;
END$$

DROP FUNCTION IF EXISTS EXISTE_DIRECCION;
CREATE FUNCTION EXISTE_DIRECCION(clave_catalogo CHAR(3)) RETURNS BOOLEAN
BEGIN
    DECLARE existe BOOLEAN;
    SELECT COUNT(*) > 0 INTO existe
    FROM direccion
    WHERE direccion.clave_catalogo = clave_catalogo;
    RETURN existe;
END$$

DROP FUNCTION IF EXISTS EXISTE_TIPO_LOTE;
CREATE FUNCTION EXISTE_TIPO_LOTE(clave_catalogo CHAR(3)) RETURNS BOOLEAN
BEGIN
    DECLARE existe BOOLEAN;
    SELECT COUNT(*) > 0 INTO existe
    FROM tipo_LOTE
    WHERE tipo_LOTE.clave_catalogo = clave_catalogo;
    RETURN existe;
END$$

DELIMITER ;